name = "stasher-website"
main = "worker.ts"
compatibility_date = "2024-01-01"

[observability]
enabled = true

[[routes]]
pattern = "stasher.dev"
zone_name = "stasher.dev"

[[routes]]
pattern = "stasher.dev/*"
zone_name = "stasher.dev"